<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFcjkavf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFcjkavf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFcjkavf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFcjkavf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFcjkavf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fcjkavf',
    'container.build_id' => '5fc61814',
    'container.build_time' => 1531835423,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFcjkavf');
